apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
components:
  - ../../../base/components/app-common

configMapGenerator:
  - name: service-name
    literals:
      - SERVICE_NAME=node-app
      - APP_PORT=8080

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app: node-app
    includeSelectors: true
    includeTemplates: true
