apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      kind: ConfigMap
      name: service-name
      fieldPath: data.APP_PORT
    targets:
      - select:
          kind: Rollout
          name: app
        fieldPaths:
          - spec.template.spec.containers.0.ports.0.containerPort

  - source:
      kind: ConfigMap
      name: service-name
      fieldPath: data.SERVICE_NAME
    targets:
      - select:
          kind: Rollout
          name: app
        fieldPaths:
          - spec.strategy.canary.canaryService
          - spec.template.spec.containers.0.envFrom.0.configMapRef.name
          - spec.template.spec.containers.0.envFrom.1.secretRef.name
        options:
          delimiter: "-"
          index: 0

  - source:
      kind: ConfigMap
      name: service-name
      fieldPath: data.SERVICE_NAME
    targets:
      - select:
          kind: Rollout
          name: app
        fieldPaths:
          - metadata.name
          - metadata.labels.app
          - metadata.labels.[app.kubernetes.io/name]
          - metadata.labels.[app.kubernetes.io/instance]
          - spec.selector.matchLabels.app
          - spec.selector.matchLabels.[app.kubernetes.io/name]
          - spec.selector.matchLabels.[app.kubernetes.io/instance]
          - spec.strategy.canary.stableService
          - spec.template.metadata.labels.app
          - spec.template.metadata.labels.[app.kubernetes.io/name]
          - spec.template.metadata.labels.[app.kubernetes.io/instance]
          - spec.template.spec.serviceAccountName
      - select:
          kind: ServiceAccount
          name: app
        fieldPaths:
          - metadata.name
      - select:
          kind: Service
          name: app
        fieldPaths:
          - metadata.name
          - metadata.labels.app
          - spec.selector.app
          - spec.selector.[app.kubernetes.io/name]
          - spec.selector.[app.kubernetes.io/instance]
      - select:
          kind: Service
          name: app-canary
        fieldPaths:
          - metadata.labels.app
          - spec.selector.app
          - spec.selector.[app.kubernetes.io/name]
          - spec.selector.[app.kubernetes.io/instance]
      - select:
          kind: HorizontalPodAutoscaler
          name: app
        fieldPaths:
          - metadata.name
          - metadata.labels.app
          - metadata.labels.[app.kubernetes.io/name]
          - metadata.labels.[app.kubernetes.io/instance]
          - spec.scaleTargetRef.name
      - select:
          kind: Ingress
          name: app
        fieldPaths:
          - metadata.name
          - spec.rules.0.http.paths.0.backend.service.name

  - source:
      kind: ConfigMap
      name: service-name
      fieldPath: data.SERVICE_NAME
    targets:
      - select:
          kind: Service
          name: app-canary
        fieldPaths:
          - metadata.name
        options:
          delimiter: "-"
          index: 0
