apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prd
    external-dns.alpha.kubernetes.io/hostname: nextjs-app.dominio.com.br
spec:
  rules:
    - host: nextjs-app.dominio.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-app
                port:
                  number: 80
  tls:
    - hosts:
        - nextjs-app.dominio.com.br
      secretName: nextjs-app-letsencrypt-secret