apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-app
resources:
- ../../base
- externalsecret.yaml
- configmap.yaml
images:
- name: app
  newName: ghcr.io/wellingtonns/node-app
  newTag: c86944244af78c4755adaca978a32004b08aad06
    
patches:
- path: patches/rollout.yaml
  target:
    kind: Rollout
    name: node-app
- path: patches/hpa.yaml
  target:
    kind: HorizontalPodAutoscaler
    name: node-app
- path: patches/ingress.yaml
  target:
    kind: Ingress
    name: node-app
