apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: python-app
resources:
- ../../base
- externalsecret.yaml
- configmap.yaml
images:
- name: app
  newName: ghcr.io/wellingtonns/python-app
  newTag: 9a93b19e6a1a329bfaa56c9f50760c78ffb85aba
    
patches:
- path: patches/rollout.yaml
  target:
    kind: Rollout
    name: python-app
- path: patches/hpa.yaml
  target:
    kind: HorizontalPodAutoscaler
    name: python-app
- path: patches/ingress.yaml
  target:
    kind: Ingress
    name: python-app
