apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example-frontend
namePrefix: example-frontend-

resources:
  - namespace.yaml
  - ../../base

images:
  - name: app-image
    newName: ghcr.io/example/example-frontend
    newTag: latest

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml

commonLabels:
  app.kubernetes.io/part-of: example-frontend
