apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-clinica
namePrefix: app-clinica-

resources:
  - namespace.yaml
  - ../../base

images:
  - name: app-image
    newName: ghcr.io/example/app-clinica
    newTag: latest

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml

commonLabels:
  app.kubernetes.io/part-of: app-clinica
