apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-clinica
resources:
- ../../base
- externalsecret.yaml
- configmap.yaml
images:
- name: app
  newName: ghcr.io/wellingtonns/app-clinica
  newTag: 1725b4ba8d4f54b0b3c7c2c4cc3be56b9e6fcb5b
    
patches:
- path: patches/rollout.yaml
  target:
    kind: Rollout
    name: app-clinica
- path: patches/hpa.yaml
  target:
    kind: HorizontalPodAutoscaler
    name: app-clinica
- path: patches/ingress.yaml
  target:
    kind: Ingress
    name: app-clinica
