apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: go-app
resources:
  - ../../base
  - externalsecret.yaml
  - configmap.yaml
images:
  - name: app
    newName: europe-west2-docker.pkg.dev/devops/name-registry/go-app
    newTag: 09737333d23d56fb096ce972f338641867a13001
    
patches:
  - target:
      kind: Rollout
      name: go-app
    path: patches/rollout.yaml
  - target:
      kind: HorizontalPodAutoscaler
      name: go-app
    path: patches/hpa.yaml
  - target:
      kind: Ingress
      name: go-app
    path: patches/ingress.yaml
