apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app
  labels:
    app: app
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: app
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: app
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
