apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: laravel-app
resources:
- ../../base
- externalsecret.yaml
- configmap.yaml
images:
- name: app
  newName: ghcr.io/wellingtonns/laravel-app
  newTag: bff9004887e15308e0f4e00986538e250f14c328
    
patches:
- path: patches/rollout.yaml
  target:
    kind: Rollout
    name: laravel-app
- path: patches/hpa.yaml
  target:
    kind: HorizontalPodAutoscaler
    name: laravel-app
- path: patches/ingress.yaml
  target:
    kind: Ingress
    name: laravel-app
