apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: laravel-app
resources:
- ../../base
- externalsecret.yaml
- configmap.yaml
images:
- name: app
  newName: ghcr.io/wellingtonns/laravel-app
  newTag: 9bb4b3c3b0a774344ad7c556b6689906e06096b3
    
patches:
- path: patches/rollout.yaml
  target:
    kind: Rollout
    name: laravel-app
- path: patches/hpa.yaml
  target:
    kind: HorizontalPodAutoscaler
    name: laravel-app
- path: patches/ingress.yaml
  target:
    kind: Ingress
    name: laravel-app
