apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-clinica
resources:
- ../../base
- externalsecret.yaml
- configmap.yaml
images:
- name: app
  newName: ghcr.io/wellingtonns/app-clinica
  newTag: dee590bd1884af5a3f167c982759fd4e5c19613e

patches:
- path: patches/rollout.yaml
  target:
    kind: Rollout
    name: app-clinica
- path: patches/hpa.yaml
  target:
    kind: HorizontalPodAutoscaler
    name: app-clinica
- path: patches/ingress.yaml
  target:
    kind: Ingress
    name: app-clinica
