apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: laravel-app-secrets
  namespace: laravel-app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: laravel-app-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: laravel-app
    rewrite:
    - regexp:
        source: "(.*)"
        target: "$1"