apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: laravel-app
resources:
- ../../base
- externalsecret.yaml
- configmap.yaml
images:
- name: app
  newName: ghcr.io/wellingtonns/laravel-app
  newTag: 155028a075a8cc5ceb8ced3039591f9c1bfa961a

patches:
- path: patches/rollout.yaml
  target:
    kind: Rollout
    name: laravel-app
- path: patches/hpa.yaml
  target:
    kind: HorizontalPodAutoscaler
    name: laravel-app
- path: patches/ingress.yaml
  target:
    kind: Ingress
    name: laravel-app
