apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: laravel-app
resources:
- ../../base
- externalsecret.yaml
- configmap.yaml
images:
- name: app
  newName: ghcr.io/wellingtonns/laravel-app
  newTag: b98ccb330632a977471c5e2ca8340ac50a2e84c7

patches:
- path: patches/rollout.yaml
  target:
    kind: Rollout
    name: laravel-app
- path: patches/hpa.yaml
  target:
    kind: HorizontalPodAutoscaler
    name: laravel-app
- path: patches/ingress.yaml
  target:
    kind: Ingress
    name: laravel-app
