apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: laravel-app
resources:
- ../../base
- externalsecret.yaml
- configmap.yaml
images:
- name: app
  newName: ghcr.io/wellingtonns/laravel-app
  newTag: 52991276f3fa94f46206f8fe90b8610b8edfd1a1

patches:
- path: patches/rollout.yaml
  target:
    kind: Rollout
    name: laravel-app
- path: patches/hpa.yaml
  target:
    kind: HorizontalPodAutoscaler
    name: laravel-app
- path: patches/ingress.yaml
  target:
    kind: Ingress
    name: laravel-app
